### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by fatinghenji** [initialencounter/koimux_bot#1]
### 日志：
```node
2023-10-19 23:45:15 [W] search Error: Hostname/IP does not match certificate's altnames: Host: ascii2d.net. is not in the cert's altnames: DNS:dtku36.xyz, DNS:dtku37.xyz, DNS:dtku39.xyz, DNS:dtku40.xyz, DNS:dtku41.xyz, DNS:dtku42.xyz, DNS:dtku43.xyz, DNS:dtku44.xyz, DNS:dtku45.xyz, DNS:fan.zfan1.xyz, DNS:fan.zfan10.xyz, DNS:fan.zfan11.xyz, DNS:fan.zfan12.xyz, DNS:fan.zfan13.xyz, DNS:fan.zfan14.xyz, DNS:fan.zfan15.xyz, DNS:fan.zfan16.xyz, DNS:fan.zfan17.xyz, DNS:fan.zfan18.xyz, DNS:fan.zfan19.xyz, DNS:fan.zfan2.xyz, DNS:fan.zfan3.xyz, DNS:fan.zfan4.xyz, DNS:fan.zfan5.xyz, DNS:fan.zfan6.xyz, DNS:fan.zfan7.xyz, DNS:fan.zfan8.xyz, DNS:fan.zfan9.xyz, DNS:free.dtku28.xyz, DNS:free.dtku36.xyz, DNS:free.dtku37.xyz, DNS:free.dtku39.xyz, DNS:free.dtku40.xyz, DNS:free.dtku41.xyz, DNS:free.dtku42.xyz, DNS:free.dtku43.xyz, DNS:free.dtku44.xyz, DNS:free.dtku45.xyz, DNS:free.free7.site, DNS:gg.dtku16.xyz, DNS:gg.dtku17.xyz, DNS:gg.dtku22.xyz, DNS:gg.dtku26.xyz, DNS:gg.dtku32.xyz, DNS:gg.dtku34.xyz, DNS:gg.dtku38.xyz, DNS:gg.freeku10.xyz, DNS:gg.gle1.xyz, DNS:gg.gle2.xyz, DNS:gg.gle3.xyz, DNS:gg.gle4.xyz, DNS:gg.gle5.xyz, DNS:gg.gle6.xyz, DNS:gg.gle7.xyz, DNS:gg.gle8.xyz, DNS:gg.gle9.xyz, DNS:gg2.freeku10.xyz, DNS:gg3.freeku10.xyz, DNS:gle1.xyz, DNS:gle2.xyz, DNS:gle3.xyz, DNS:gle4.xyz, DNS:gle5.xyz, DNS:gle6.xyz, DNS:gle7.xyz, DNS:gle8.xyz, DNS:gle9.xyz, DNS:www.ytb11.xyz, DNS:www.ytb13.xyz, DNS:www.ytb14.xyz, DNS:www.ytb15.xyz, DNS:ytb11.xyz, DNS:ytb13.xyz, DNS:ytb14.xyz, DNS:ytb15.xyz, DNS:zfan10.xyz, DNS:zfan11.xyz, DNS:zfan12.xyz, DNS:zfan13.xyz, DNS:zfan14.xyz, DNS:zfan15.xyz, DNS:zfan16.xyz, DNS:zfan17.xyz, DNS:zfan18.xyz, DNS:zfan19.xyz, DNS:zfan2.xyz, DNS:zfan3.xyz, DNS:zfan4.xyz, DNS:zfan5.xyz, DNS:zfan6.xyz, DNS:zfan7.xyz, DNS:zfan8.xyz, DNS:zfan9.xyz
                            at request (/root/koimux_bot/node_modules/cordis-axios/lib/index.js:269:21)
                            at http (/root/koimux_bot/node_modules/cordis-axios/lib/index.js:288:30)
                            at _Quester.post (/root/koimux_bot/node_modules/cordis-axios/lib/index.js:185:16)
                            at default_1 (/root/koimux_bot/node_modules/koishi-plugin-image-search/lib/ascii2d.js:17:38)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async searchUrl (/root/koimux_bot/node_modules/koishi-plugin-image-search/lib/index.js:51:28)
                            at async next (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:848:16)
                            at async _Processor._handleMessage (/root/koimux_bot/node_modules/@koishijs/core/lib/index.cjs:859:22)
```
### 复现步骤：
1. 安装[image-search](https://github.com/koishijs/koishi-plugin-image-search)插件
2. 启动[clash-meta-for-android](https://f-droid.org/packages/com.github.metacubex.clash.meta/)，作为翻墙工具
3. 调用该插件
4. 报错

**Comment by initialencounter** [comment]
无法复现，你填写了proxyAgent吗？这个是不需要填写的，ascii2d 搜图咋用啊，我这边能访问但是报错 403
